techpack: data: Add void argument to old-style zero prototype functions
Newer clang builds complain about old-style function declarations
not having any prototype assigned. The missing arguments are
triggering the Wstrict-prototype warns. Explicitly add the
`void` argument to satisfy the compiler.

../techpack/data/drivers/rmnet/perf/rmnet_perf_opt.c:715:27: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
rmnet_perf_free_hash_table()
                          ^
                           void

Signed-off-by: alanndz <alanndz7@gmail.com>